[[contribution-guidelines]]
= 贡献指南

== 代码格式化与 Javadoc

在提交 PR 之前，请运行以下命令以确保代码格式正确并生成 Javadoc：

```
./mvnw spring-javaformat:apply javadoc:javadoc -Pjavadoc
```

`-Pjavadoc` 是一个用于启用 Javadoc 处理的配置文件，这样在开发时可以避免较长的构建时间。

== 新 AI 模型实现的贡献流程

本节概述了贡献新 AI 模型实现的步骤。
AI 模型差异很大，输入和输出多种多样——从将文本输入转为文本输出的聊天模型，到根据文本描述生成图像的文本转图像模型。
复杂的模型甚至可能同时处理多种输入和输出类型，例如结合文本、图片和视频生成混合媒体输出。

要贡献新模型，请遵循以下步骤：

. *创建底层客户端 API 类*：如果没有现有的 Java 客户端适用于该 AI 模型，则需要开发一个底层客户端 API 类。通常涉及使用 Spring Framework 的 `RestClient` 类，类似于 `OpenAiApi` 类。

. *创建模型实现*
确保你的客户端符合 link:https://docs.spring.io/spring-ai/reference/api/generic-model.html[通用模型 API]。
如果模型的输入和输出已被支持，请使用现有的请求和响应类。
如果不支持，则为通用模型 API 创建新的类，并建立新的 Java 包。
在记录个人身份信息（PII）时，请使用 https://github.com/spring-projects/spring-ai/tree/main/spring-ai-core/src/main/java/org/springframework/ai/util/LoggingMarkers.java[`PII_MARKER`] Slf4j 标记进行标记。

. *实现自动配置和 Spring Boot Starter*：此步骤包括创建必要的自动配置和 Spring Boot Starter，以便在 Spring Boot 应用中轻松实例化新模型。

. *编写测试*：所有新类都应配备全面的测试。现有测试可以作为结构和实现的有用参考。

. *完善文档*：确保你的文档遵循现有格式。有关建议结构和格式的示例，请参阅 link:https://docs.spring.io/spring-ai/reference/api/chat/openai-chat.html[Open AI Chat 文档]。

通过遵循这些指南，我们可以在遵循统一实现和文档模式的同时，大幅扩展框架支持的模型范围。
