= MiniMax 聊天

Spring AI支持来自MiniMax的各种AI语言模型。您可以与MiniMax语言模型交互，并基于MiniMax模型创建多语言对话助手。

== 前提条件

您需要创建一个MiniMax API来访问MiniMax语言模型。

在https://www.minimaxi.com/login[MiniMax注册页面]创建账户，并在https://www.minimaxi.com/user-center/basic-information/interface-key[API密钥页面]生成令牌。

Spring AI项目定义了一个名为`spring.ai.minimax.api-key`的配置属性，您应该将其设置为从API密钥页面获取的`API密钥`值。

您可以在`application.properties`文件中设置此配置属性：

[source,properties]
----
spring.ai.minimax.api-key=<your-minimax-api-key>
----

为了在处理API密钥等敏感信息时增强安全性，您可以使用Spring表达式语言(SpEL)来引用环境变量：

[source,yaml]
----
# 在application.yml中
spring:
  ai:
    minimax:
      api-key: ${MINIMAX_API_KEY}
----

[source,bash]
----
# 在您的环境或.env文件中
export MINIMAX_API_KEY=<your-minimax-api-key>
----

您也可以在应用程序代码中以编程方式设置此配置：

[source,java]
----
// 从安全源或环境变量中获取API密钥
String apiKey = System.getenv("MINIMAX_API_KEY");
----

=== 添加仓库和BOM

Spring AI构件发布在Maven Central和Spring Snapshot仓库中。
请参阅xref:getting-started.adoc#artifact-repositories[构件仓库]部分，将这些仓库添加到您的构建系统中。

为了帮助依赖管理，Spring AI提供了BOM（物料清单）以确保在整个项目中使用一致版本的Spring AI。请参阅xref:getting-started.adoc#dependency-management[依赖管理]部分，将Spring AI BOM添加到您的构建系统中。

== 自动配置

[NOTE]
====
Spring AI自动配置、starter模块的构件名称发生了重大变化。
请参阅https://docs.spring.io/spring-ai/reference/upgrade-notes.html[升级说明]了解更多信息。
====

Spring AI为MiniMax聊天客户端提供Spring Boot自动配置。
要启用它，请在项目的Maven `pom.xml`文件中添加以下依赖：

[source, xml]
----
<dependency>
    <groupId>org.springframework.ai</groupId>
    <artifactId>spring-ai-starter-model-minimax</artifactId>
</dependency>
----

或添加到您的Gradle `build.gradle`构建文件中。

[source,groovy]
----
dependencies {
    implementation 'org.springframework.ai:spring-ai-starter-model-minimax'
}
----

提示：请参阅xref:getting-started.adoc#dependency-management[依赖管理]部分，将Spring AI BOM添加到您的构建文件中。

=== 聊天属性

==== 重试属性

前缀`spring.ai.retry`用作属性前缀，允许您配置MiniMax聊天模型的重试机制。

[cols="3,5,1", stripes=even]
|====
| 属性 | 描述 | 默认值

| spring.ai.retry.max-attempts   | 最大重试尝试次数。 |  10
| spring.ai.retry.backoff.initial-interval | 指数退避策略的初始睡眠持续时间。 |  2秒
| spring.ai.retry.backoff.multiplier | 退避间隔乘数。 |  5
| spring.ai.retry.backoff.max-interval | 最大退避持续时间。 |  3分钟
| spring.ai.retry.on-client-errors | 如果为false，对于`4xx`客户端错误代码抛出NonTransientAiException，不尝试重试 | false
| spring.ai.retry.exclude-on-http-codes | 不应触发重试的HTTP状态代码列表（例如抛出NonTransientAiException）。 | 空
| spring.ai.retry.on-http-codes | 应触发重试的HTTP状态代码列表（例如抛出TransientAiException）。 | 空
|====

==== 连接属性

前缀`spring.ai.minimax`用作属性前缀，允许您连接到MiniMax。

[cols="3,5,1", stripes=even]
|====
| 属性 | 描述 | 默认值

| spring.ai.minimax.base-url   | 要连接的URL |  https://api.minimax.chat
| spring.ai.minimax.api-key    | API密钥           |  -
|====

==== 配置属性

[NOTE]
====
聊天自动配置的启用和禁用现在通过前缀为`spring.ai.model.chat`的顶级属性进行配置。

要启用，spring.ai.model.chat=minimax（默认启用）

要禁用，spring.ai.model.chat=none（或任何不匹配minimax的值）

此更改是为了允许多个模型的配置。
====

前缀`spring.ai.minimax.chat`是允许您配置MiniMax聊天模型实现的属性前缀。

[cols="3,5,1", stripes=even]
|====
| 属性 | 描述 | 默认值

| spring.ai.minimax.chat.enabled (已移除且不再有效) | 启用MiniMax聊天模型。  | true
| spring.ai.model.chat | 启用MiniMax聊天模型。  | minimax
| spring.ai.minimax.chat.base-url | 可选覆盖spring.ai.minimax.base-url以提供聊天特定的url |  https://api.minimax.chat
| spring.ai.minimax.chat.api-key | 可选覆盖spring.ai.minimax.api-key以提供聊天特定的api-key |  -
| spring.ai.minimax.chat.options.model | 这是要使用的MiniMax聊天模型 | `abab6.5g-chat`（`abab5.5-chat`、`abab5.5s-chat`、`abab6.5-chat`、`abab6.5g-chat`、`abab6.5t-chat`和`abab6.5s-chat`指向最新的模型版本）
| spring.ai.minimax.chat.options.maxTokens | 在聊天完成中生成的最大令牌数。输入令牌和生成令牌的总长度受模型上下文长度的限制。 | -
| spring.ai.minimax.chat.options.temperature | 用于控制生成完成项的明显创造性的采样温度。较高的值将使输出更随机，而较低的值将使结果更集中和确定性。不建议为相同的完成请求同时修改temperature和top_p，因为这两个设置的交互很难预测。 | 0.7
| spring.ai.minimax.chat.options.topP | 温度采样的替代方案，称为核采样，其中模型考虑具有top_p概率质量的令牌的结果。所以0.1意味着只考虑构成前10%概率质量的令牌。我们通常建议修改这个或temperature，但不要同时修改两者。 | 1.0
| spring.ai.minimax.chat.options.n | 为每个输入消息生成多少个聊天完成选项。请注意，您将根据所有选项中生成的令牌数量收费。默认值为1，不能大于5。具体来说，当temperature非常小且接近0时，我们只能返回1个结果。如果此时n已设置且>1，服务将返回非法输入参数（invalid_request_error） | 1
| spring.ai.minimax.chat.options.presencePenalty | -2.0到2.0之间的数字。正值根据新令牌是否出现在文本中来惩罚它们，增加模型讨论新主题的可能性。 |  0.0f
| spring.ai.minimax.chat.options.frequencyPenalty | -2.0到2.0之间的数字。正值根据新令牌在文本中的现有频率来惩罚它们，降低模型逐字重复相同行的可能性。 | 0.0f
| spring.ai.minimax.chat.options.stop | 模型将停止生成由stop指定的字符，目前仅支持单个停止词，格式为["stop_word1"] | -
|====

注意：您可以为`ChatModel`实现覆盖通用的`spring.ai.minimax.base-url`和`spring.ai.minimax.api-key`。
如果设置了`spring.ai.minimax.chat.base-url`和`spring.ai.minimax.chat.api-key`属性，它们将优先于通用属性。
如果您想为不同的模型和不同的模型端点使用不同的MiniMax账户，这很有用。

提示：所有以`spring.ai.minimax.chat.options`为前缀的属性都可以通过在`Prompt`调用中添加请求特定的<<chat-options>>在运行时覆盖。

== 运行时选项 [[chat-options]]

link:https://github.com/spring-projects/spring-ai/blob/main/models/spring-ai-minimax/src/main/java/org/springframework/ai/minimax/MiniMaxChatOptions.java[MiniMaxChatOptions.java]提供模型配置，如要使用的模型、温度、频率惩罚等。

在启动时，可以通过`MiniMaxChatModel(api, options)`构造函数或`spring.ai.minimax.chat.options.*`属性配置默认选项。

在运行时，您可以通过在`Prompt`调用中添加新的、请求特定的选项来覆盖默认选项。
例如，要覆盖特定请求的默认模型和温度：

[source,java]
----
ChatResponse response = chatModel.call(
    new Prompt(
        "Generate the names of 5 famous pirates.",
        MiniMaxChatOptions.builder()
            .model(MiniMaxApi.ChatModel.ABAB_6_5_S_Chat.getValue())
            .temperature(0.5)
        .build()
    ));
----

提示：除了模型特定的link:https://github.com/spring-projects/spring-ai/blob/main/models/spring-ai-minimax/src/main/java/org/springframework/ai/minimax/MiniMaxChatOptions.java[MiniMaxChatOptions]外，您还可以使用可移植的https://github.com/spring-projects/spring-ai/blob/main/spring-ai-client-chat/src/main/java/org/springframework/ai/chat/ChatOptions.java[ChatOptions]实例，使用https://github.com/spring-projects/spring-ai/blob/main/spring-ai-client-chat/src/main/java/org/springframework/ai/chat/ChatOptionsBuilder.java[ChatOptionsBuilder#builder()]创建。

== 示例控制器

https://start.spring.io/[创建]一个新的Spring Boot项目，并将`spring-ai-starter-model-minimax`添加到您的pom（或gradle）依赖中。

在`src/main/resources`目录下添加一个`application.properties`文件，以启用和配置MiniMax聊天模型：

[source,application.properties]
----
spring.ai.minimax.api-key=YOUR_API_KEY
spring.ai.minimax.chat.options.model=abab6.5g-chat
spring.ai.minimax.chat.options.temperature=0.7
----

提示：用您的MiniMax凭据替换`api-key`。

这将创建一个`MiniMaxChatModel`实现，您可以将其注入到您的类中。
以下是一个简单的`@Controller`类示例，它使用聊天模型进行文本生成。

[source,java]
----
@RestController
public class ChatController {

    private final MiniMaxChatModel chatModel;

    @Autowired
    public ChatController(MiniMaxChatModel chatModel) {
        this.chatModel = chatModel;
    }

    @GetMapping("/ai/generate")
    public Map generate(@RequestParam(value = "message", defaultValue = "Tell me a joke") String message) {
        return Map.of("generation", this.chatModel.call(message));
    }

    @GetMapping("/ai/generateStream")
	public Flux<ChatResponse> generateStream(@RequestParam(value = "message", defaultValue = "Tell me a joke") String message) {
        var prompt = new Prompt(new UserMessage(message));
        return this.chatModel.stream(prompt);
    }
}
----

== 手动配置

link:https://github.com/spring-projects/spring-ai/blob/main/models/spring-ai-minimax/src/main/java/org/springframework/ai/minimax/MiniMaxChatModel.java[MiniMaxChatModel]实现了`ChatModel`和`StreamingChatModel`，并使用<<low-level-api>>连接到MiniMax服务。

在项目的Maven `pom.xml`文件中添加`spring-ai-minimax`依赖：

[source, xml]
----
<dependency>
    <groupId>org.springframework.ai</groupId>
    <artifactId>spring-ai-minimax</artifactId>
</dependency>
----

或添加到您的Gradle `build.gradle`构建文件中。

[source,groovy]
----
dependencies {
    implementation 'org.springframework.ai:spring-ai-minimax'
}
----

提示：请参阅xref:getting-started.adoc#dependency-management[依赖管理]部分，将Spring AI BOM添加到您的构建文件中。

接下来，创建一个`MiniMaxChatModel`并使用它进行文本生成：

[source,java]
----
var miniMaxApi = new MiniMaxApi(System.getenv("MINIMAX_API_KEY"));

var chatModel = new MiniMaxChatModel(this.miniMaxApi, MiniMaxChatOptions.builder()
                .model(MiniMaxApi.ChatModel.ABAB_6_5_S_Chat.getValue())
                .temperature(0.4)
                .maxTokens(200)
                .build());

ChatResponse response = this.chatModel.call(
    new Prompt("Generate the names of 5 famous pirates."));

// 或使用流式响应
Flux<ChatResponse> streamResponse = this.chatModel.stream(
    new Prompt("Generate the names of 5 famous pirates."));
----

`MiniMaxChatOptions`提供聊天请求的配置信息。
`MiniMaxChatOptions.Builder`是一个流畅的选项构建器。

=== 低级MiniMaxApi客户端 [[low-level-api]]

link:https://github.com/spring-projects/spring-ai/blob/main/models/spring-ai-minimax/src/main/java/org/springframework/ai/minimax/api/MiniMaxApi.java[MiniMaxApi]提供了link:https://www.minimaxi.com/document/guides/chat-model/V2[MiniMax API]的轻量级Java客户端。

以下是一个简单的代码片段，展示如何以编程方式使用API：

[source,java]
----
MiniMaxApi miniMaxApi =
    new MiniMaxApi(System.getenv("MINIMAX_API_KEY"));

ChatCompletionMessage chatCompletionMessage =
    new ChatCompletionMessage("Hello world", Role.USER);

// 同步请求
ResponseEntity<ChatCompletion> response = this.miniMaxApi.chatCompletionEntity(
    new ChatCompletionRequest(List.of(this.chatCompletionMessage), MiniMaxApi.ChatModel.ABAB_6_5_S_Chat.getValue(), 0.7f, false));

// 流式请求
Flux<ChatCompletionChunk> streamResponse = this.miniMaxApi.chatCompletionStream(
        new ChatCompletionRequest(List.of(this.chatCompletionMessage), MiniMaxApi.ChatModel.ABAB_6_5_S_Chat.getValue(), 0.7f, true));
----

请参阅https://github.com/spring-projects/spring-ai/blob/main/models/spring-ai-minimax/src/main/java/org/springframework/ai/minimax/api/MiniMaxApi.java[MiniMaxApi.java]的JavaDoc获取更多信息。

=== Web搜索聊天 [[web-search]]

MiniMax模型支持网络搜索功能。网络搜索功能允许您搜索网络信息并在聊天响应中返回结果。

有关网络搜索的更多信息，请参阅https://platform.minimaxi.com/document/ChatCompletion%20v2[MiniMax ChatCompletion]。

以下是一个简单的代码片段，展示如何使用网络搜索：

[source,java]
----
UserMessage userMessage = new UserMessage(
        "How many gold medals has the United States won in total at the 2024 Olympics?");

List<Message> messages = new ArrayList<>(List.of(this.userMessage));

List<MiniMaxApi.FunctionTool> functionTool = List.of(MiniMaxApi.FunctionTool.webSearchFunctionTool());

MiniMaxChatOptions options = MiniMaxChatOptions.builder()
    .model(MiniMaxApi.ChatModel.ABAB_6_5_S_Chat.value)
    .tools(this.functionTool)
    .build();


// 同步请求
ChatResponse response = chatModel.call(new Prompt(this.messages, this.options));

// 流式请求
Flux<ChatResponse> streamResponse = chatModel.stream(new Prompt(this.messages, this.options));
----

==== MiniMaxApi示例
* link:https://github.com/spring-projects/spring-ai/blob/main/models/spring-ai-minimax/src/test/java/org/springframework/ai/minimax/api/MiniMaxApiIT.java[MiniMaxApiIT.java]测试提供了一些关于如何使用轻量级库的一般示例。

* link:https://github.com/spring-projects/spring-ai/blob/main/models/spring-ai-minimax/src/test/java/org/springframework/ai/minimax/api/MiniMaxApiToolFunctionCallIT.java[MiniMaxApiToolFunctionCallIT.java]测试展示了如何使用低级API调用工具函数。
基于https://docs.mistral.ai/guides/function-calling/[Mistral AI函数调用]教程。
