[[AiMetadata]]
= AI 元数据

使用 AI（如 OpenAI 的 ChatGPT）会消耗资源并生成基于使用情况和通过 API 向 AI 发出的请求的指标，这些指标由 AI 提供商返回。
消耗通常以在给定时间段（如每月）内发出的请求或使用的令牌形式出现，AI 提供商使用这些来衡量消耗并重置限制。
您的速率限制直接由您注册 AI 提供商时选择的计划决定。例如，您可以通过以下链接查看 OpenAI 的 https://platform.openai.com/docs/guides/rate-limits?context=tier-free[速率限制] 和 https://openai.com/pricing#language-models[计划] 的详细信息。

为了帮助深入了解您的 AI（模型）消耗和一般使用情况，Spring AI 提供了一个 API 来检查 AI 提供商在其 API 中返回的元数据。

Spring AI 定义了 3 个主要接口来检查这些指标：`GenerationMetadata`、`RateLimit` 和 `Usage`。所有这些接口都可以从 AI 请求发起并返回的 `ChatResponse` 中以编程方式访问。

[[AiMetadata-GenerationMetadata]]
== `GenerationMetadata` 接口

`GenerationMetadata` 接口定义如下：

.GenerationMetadata 接口
[source,java]
----
interface GenerationMetadata {

	default RateLimit getRateLimit() {
		return RateLimit.NULL;
	}

	default Usage getUsage() {
		return Usage.NULL;
	}

}
----

当通过 AI 提供商的 API 发出 AI 请求并返回 AI 响应时，Spring AI 会自动创建 `GenerationMetadata` 的实例。您可以使用以下方式从 `ChatResponse` 访问 AI 提供商元数据：

.从 `ChatResponse` 获取 `GenerationMetadata` 的访问权限
[source,java]
----
@Service
class MyService {

	ApplicationObjectType askTheAi(ServiceRequest request) {

        Prompt prompt = createPrompt(request);

        ChatResponse response = chatModel.call(prompt);

        // 处理聊天响应

        GenerationMetadata metadata = response.getMetadata();

        // 检查 AI 提供商 API 返回的聊天响应中的 AI 元数据

        Long totalTokensUsedInAiPromptAndResponse = metadata.getUsage().getTotalTokens();

        // 以某种方式处理这些信息
	}
}
----

您可以想象，您可以使用 AI 来限制自己的 Spring 应用程序的速率，或者以自动化、智能和实时的方式限制影响令牌使用的 `Prompt` 大小。
至少，您可以简单地收集这些指标来监控和报告您的消耗情况。

[[AiMetadata-RateLimit]]
== RateLimit

`RateLimit` 接口提供对 AI 提供商在发出 AI 请求时返回的关于您的 API 使用情况的实际信息的访问。

.`RateLimit` 接口
[source,java]
----
interface RateLimit {

	Long getRequestsLimit();

	Long getRequestsRemaining();

	Duration getRequestsReset();

	Long getTokensLimit();

	Long getTokensRemaining();

	Duration getTokensReset();

}
----

`requestsLimit` 和 `requestsRemaining` 让您知道基于您在注册时选择的 AI 提供商计划，您可以在给定时间段内发出的 AI 请求总数以及您的剩余余额。`requestsReset` 返回一个 `Duration`，表示在时间段到期和您的限制根据您选择的计划重置之前的时间。

`tokensLimit`、`tokensRemaining` 和 `tokensReset` 的方法与请求的方法类似，但专注于令牌限制、余额和重置。

可以从 `GenerationMetadata` 获取 `RateLimit` 实例，如下所示：

.从 `GenerationMetadata` 获取 `RateLimit` 的访问权限
[source,java]
----
RateLimit rateLimit = generationMetadata.getRateLimit();

Long tokensRemaining = this.rateLimit.getTokensRemaining();

// 对 RateLimit 元数据做一些有趣的事情
----

对于像 OpenAI 这样的 AI 提供商，速率限制元数据是在其（REST）API 的 https://platform.openai.com/docs/guides/rate-limits/rate-limits-in-headers[HTTP 头] 中返回的，可以通过 HTTP 客户端（如 OkHttp）访问。

因为这可能是一个成本较高的操作，所以必须显式启用速率限制 AI 元数据的收集。您可以在 Spring Boot application.properties 中使用 Spring AI 属性启用此收集；例如：

.启用从 AI 元数据收集 API 速率限制
[source,properties]
----
# Spring Boot application.properties
spring.ai.openai.metadata.rate-limit-metrics-enabled=true
----

[[AiMetadata-Usage]]
== Usage

如 <<AiMetadata-GenerationMetadata,上面>> 所示，可以从 `GenerationMetadata` 对象获取 `Usage` 数据。`Usage` 接口定义如下：

.`Usage` 接口
[source,java]
----
interface Usage {

	Long getPromptTokens();

	Long getGenerationTokens();

	default Long getTotalTokens() {
		return getPromptTokens() + getGenerationTokens();
	}

}
----

方法名称是不言自明的，但告诉您 AI 处理 `Prompt` 和生成响应所需的令牌。

`totalTokens` 是 `promptTokens` 和 `generationTokens` 的总和。Spring AI 默认计算这个值，但信息是从 OpenAI 的 AI 响应中返回的。
