[[docker-compose]]
= Docker Compose

Spring AI 提供了 Spring Boot 自动配置，用于建立与通过 Docker Compose 运行的模型服务或向量存储的连接。
要启用它，请将以下依赖项添加到项目的 Maven `pom.xml` 文件中：

[source,xml]
----
<dependency>
   <groupId>org.springframework.ai</groupId>
   <artifactId>spring-ai-spring-boot-docker-compose</artifactId>
</dependency>
----

或添加到您的 Gradle `build.gradle` 构建文件中。

[source,groovy]
----
dependencies {
    implementation 'org.springframework.ai:spring-ai-spring-boot-docker-compose'
}
----

提示：请参阅 xref:getting-started.adoc#dependency-management[依赖管理] 部分，将 Spring AI BOM 添加到您的构建文件中。

== 服务连接

`spring-ai-spring-boot-docker-compose` 模块中提供了以下服务连接工厂：

[cols="|,|"]
|====
| 连接详情 | 匹配条件
| `AwsOpenSearchConnectionDetails`
| 名为 `localstack/localstack` 的容器

| `ChromaConnectionDetails`
| 名为 `chromadb/chroma`, `ghcr.io/chroma-core/chroma` 的容器

| `MongoConnectionDetails`
| 名为 `mongodb/mongodb-atlas-local` 的容器

| `OllamaConnectionDetails`
| 名为 `ollama/ollama` 的容器

| `OpenSearchConnectionDetails`
| 名为 `opensearchproject/opensearch` 的容器

| `QdrantConnectionDetails`
| 名为 `qdrant/qdrant` 的容器

| `TypesenseConnectionDetails`
| 名为 `typesense/typesense` 的容器

| `WeaviateConnectionDetails`
| 名为 `semitechnologies/weaviate`, `cr.weaviate.io/semitechnologies/weaviate` 的容器
|====
