[[testcontainers]]
= Testcontainers

Spring AI 提供了 Spring Boot 自动配置，用于建立与通过 Testcontainers 运行的模型服务或向量存储的连接。要启用它，请将以下依赖项添加到项目的 Maven `pom.xml` 文件中：

[source,xml]
----
<dependency>
   <groupId>org.springframework.ai</groupId>
   <artifactId>spring-ai-spring-boot-testcontainers</artifactId>
</dependency>
----

或添加到 Gradle `build.gradle` 构建文件中。

[source,groovy]
----
dependencies {
    implementation 'org.springframework.ai:spring-ai-spring-boot-testcontainers'
}
----

提示：请参考 xref:getting-started.adoc#dependency-management[依赖管理] 部分，将 Spring AI BOM 添加到您的构建文件中。

== 服务连接

`spring-ai-spring-boot-testcontainers` 模块中提供了以下服务连接工厂：

[cols="|,|"]
|====
| 连接详情 | 匹配条件

| `AwsOpenSearchConnectionDetails`
| 类型为 `LocalStackContainer` 的容器

| `ChromaConnectionDetails`
| 类型为 `ChromaDBContainer` 的容器

| `MilvusServiceClientConnectionDetails`
| 类型为 `MilvusContainer` 的容器

| `MongoConnectionDetails`
| 类型为 `MongoDBAtlasLocalContainer` 的容器

| `OllamaConnectionDetails`
| 类型为 `OllamaContainer` 的容器

| `OpenSearchConnectionDetails`
| 类型为 `OpensearchContainer` 的容器

| `QdrantConnectionDetails`
| 类型为 `QdrantContainer` 的容器

| `TypesenseConnectionDetails`
| 类型为 `TypesenseContainer` 的容器

| `WeaviateConnectionDetails`
| 类型为 `WeaviateContainer` 的容器
|====
