= Ollama 嵌入

使用 https://ollama.ai/[Ollama]，您可以在本地运行各种 https://ollama.com/search?c=embedding[AI 模型] 并从中生成嵌入。
嵌入是浮点数的向量（列表）。
两个向量之间的距离衡量它们的相关性。
小距离表示高相关性，大距离表示低相关性。

`OllamaEmbeddingModel` 实现利用了 Ollama https://github.com/ollama/ollama/blob/main/docs/api.md#generate-embeddings[嵌入 API] 端点。

== 前提条件

您首先需要访问 Ollama 实例。有几种选择，包括：

* 在本地机器上 link:https://ollama.com/download[下载并安装 Ollama]。
* 通过 xref:api/testcontainers.adoc[Testcontainers] 配置和运行 Ollama。
* 通过 xref:api/cloud-bindings.adoc[Kubernetes 服务绑定] 绑定到 Ollama 实例。

您可以从 https://ollama.com/search?c=embedding[Ollama 模型库] 中拉取要在应用程序中使用的模型：

[source,shellscript]
----
ollama pull <model-name>
----


您还可以拉取任何数千个免费的 link:https://huggingface.co/models?library=gguf&sort=trending[GGUF Hugging Face 模型]：

[source,shellscript]
----
ollama pull hf.co/<username>/<model-repository>
----

或者，您可以启用自动下载任何所需模型的选项：xref:auto-pulling-models[自动拉取模型]。

== 自动配置

[NOTE]
====
Spring AI 自动配置、启动器模块的构件名称发生了重大变化。
请参考 https://docs.spring.io/spring-ai/reference/upgrade-notes.html[升级说明] 了解更多信息。
====

Spring AI 为 Azure Ollama 嵌入模型提供了 Spring Boot 自动配置。
要启用它，请在项目的 Maven `pom.xml` 或 Gradle `build.gradle` 构建文件中添加以下依赖：

[tabs]
======
Maven::
+
[source,xml]
----
<dependency>
   <groupId>org.springframework.ai</groupId>
   <artifactId>spring-ai-starter-model-ollama</artifactId>
</dependency>
----

Gradle::
+
[source,groovy]
----
dependencies {
    implementation 'org.springframework.ai:spring-ai-starter-model-ollama'
}
----
======

提示：请参考 xref:getting-started.adoc#dependency-management[依赖管理] 部分，将 Spring AI BOM 添加到您的构建文件中。
Spring AI 构件发布在 Maven Central 和 Spring Snapshot 仓库中。
请参考仓库部分，将这些仓库添加到您的构建系统中。

=== 基本属性

前缀 `spring.ai.ollama` 是配置与 Ollama 连接的属性前缀

[cols="3,6,1"]
|====
| 属性 | 描述 | 默认值
| spring.ai.ollama.base-url | Ollama API 服务器运行的基础 URL。 | `http://localhost:11434`
|====

以下是初始化 Ollama 集成和 xref:auto-pulling-models[自动拉取模型] 的属性。

[cols="3,6,1"]
|====
| 属性 | 描述 | 默认值
| spring.ai.ollama.init.pull-model-strategy | 是否在启动时拉取模型以及如何拉取。 | `never`
| spring.ai.ollama.init.timeout | 等待模型拉取的时间。 | `5m`
| spring.ai.ollama.init.max-retries | 模型拉取操作的最大重试次数。 | `0`
| spring.ai.ollama.init.embedding.include | 在初始化任务中包含此类型的模型。 | `true`
| spring.ai.ollama.init.embedding.additional-models | 除了通过默认属性配置的模型之外，还要初始化的其他模型。 | `[]`
|====

=== 嵌入属性

[NOTE]
====
嵌入自动配置的启用和禁用现在通过前缀为 `spring.ai.model.embedding` 的顶级属性进行配置。

要启用，spring.ai.model.embedding=ollama（默认启用）

要禁用，spring.ai.model.embedding=none（或任何不匹配 ollama 的值）

此更改是为了允许多个模型的配置。
====

前缀 `spring.ai.ollama.embedding.options` 是配置 Ollama 嵌入模型的属性前缀。
它包括 Ollama 请求（高级）参数，如 `model`、`keep-alive` 和 `truncate`，以及 Ollama 模型 `options` 属性。

以下是 Ollama 嵌入模型的高级请求参数：

[cols="4,5,1", stripes=even]
|====
| 属性 | 描述 | 默认值
| spring.ai.ollama.embedding.enabled（已移除且不再有效）     | 启用 Ollama 嵌入模型自动配置。 | true
| spring.ai.model.embedding      | 启用 Ollama 嵌入模型自动配置。 | ollama
| spring.ai.ollama.embedding.options.model  | 要使用的 https://github.com/ollama/ollama?tab=readme-ov-file#model-library[支持的模型] 的名称。
您可以使用专用的 https://ollama.com/search?c=embedding[嵌入模型] 类型 | mistral
| spring.ai.ollama.embedding.options.keep_alive  | 控制模型在请求后保持在内存中的时间 | 5m
| spring.ai.ollama.embedding.options.truncate  | 截断每个输入的末尾以适应上下文长度。如果为 false 且超出上下文长度则返回错误。  | true
|====

其余的 `options` 属性基于 link:https://github.com/ollama/ollama/blob/main/docs/modelfile.md#valid-parameters-and-values[Ollama 有效参数和值] 和 link:https://github.com/ollama/ollama/blob/main/api/types.go[Ollama 类型]。默认值基于：link:https://github.com/ollama/ollama/blob/b538dc3858014f94b099730a592751a5454cab0a/api/types.go#L364[Ollama 类型默认值]。

[cols="4,5,1", stripes=even]
|====
| 属性 | 描述 | 默认值
| spring.ai.ollama.embedding.options.numa              | 是否使用 NUMA。                                           | false
| spring.ai.ollama.embedding.options.num-ctx           | 设置用于生成下一个令牌的上下文窗口大小。 | 2048
| spring.ai.ollama.embedding.options.num-batch         | 提示处理最大批处理大小。 | 512
| spring.ai.ollama.embedding.options.num-gpu           | 发送到 GPU 的层数。在 macOS 上默认为 1 以启用 metal 支持，0 表示禁用。1 表示 NumGPU 应该动态设置 | -1
| spring.ai.ollama.embedding.options.main-gpu          | 使用多个 GPU 时，此选项控制哪个 GPU 用于小张量，对于这些小张量，在所有 GPU 上分割计算的开销不值得。相关 GPU 将使用稍多的 VRAM 来存储临时结果的暂存缓冲区。 | 0
| spring.ai.ollama.embedding.options.low-vram          | -                                                             | false
| spring.ai.ollama.embedding.options.f16-kv            | -                                                             | true
| spring.ai.ollama.embedding.options.logits-all        | 返回所有令牌的 logits，而不仅仅是最后一个。要启用完成返回 logprobs，这必须为 true。 | -
| spring.ai.ollama.embedding.options.vocab-only        | 仅加载词汇表，不加载权重。 | -
| spring.ai.ollama.embedding.options.use-mmap          | 默认情况下，模型被映射到内存中，这允许系统根据需要仅加载模型的必要部分。但是，如果模型大于您的总 RAM 量或如果您的系统可用内存不足，使用 mmap 可能会增加页面调出的风险，从而对性能产生负面影响。禁用 mmap 会导致加载时间变慢，但如果您不使用 mlock，可能会减少页面调出。请注意，如果模型大于总 RAM 量，关闭 mmap 将阻止模型加载。 | null
| spring.ai.ollama.embedding.options.use-mlock         | 将模型锁定在内存中，防止在内存映射时被换出。这可以提高性能，但通过要求更多 RAM 运行并可能减慢加载时间（因为模型加载到 RAM 中）来换取内存映射的一些优势。 | false
| spring.ai.ollama.embedding.options.num-thread        | 设置计算期间使用的线程数。默认情况下，Ollama 将检测此值以获得最佳性能。建议将此值设置为系统具有的物理 CPU 核心数（而不是逻辑核心数）。0 = 让运行时决定 | 0
| spring.ai.ollama.embedding.options.num-keep          | -                                                             | 4
| spring.ai.ollama.embedding.options.seed              | 设置用于生成的随机数种子。将此设置为特定数字将使模型为相同的提示生成相同的文本。  | -1
| spring.ai.ollama.embedding.options.num-predict       | 生成文本时预测的最大令牌数。（-1 = 无限生成，-2 = 填充上下文） | -1
| spring.ai.ollama.embedding.options.top-k             | 减少生成无意义内容的概率。较高的值（例如，100）将给出更多样化的答案，而较低的值（例如，10）将更保守。  | 40
| spring.ai.ollama.embedding.options.top-p             | 与 top-k 一起工作。较高的值（例如，0.95）将导致更多样化的文本，而较低的值（例如，0.5）将生成更专注和保守的文本。  | 0.9
| spring.ai.ollama.embedding.options.min-p             | top_p 的替代方案，旨在确保质量和多样性的平衡。参数 p 表示令牌被考虑的最小概率，相对于最可能令牌的概率。例如，当 p=0.05 且最可能令牌的概率为 0.9 时，值小于 0.045 的 logits 将被过滤掉。  | 0.0
| spring.ai.ollama.embedding.options.tfs-z             | 使用尾部自由采样来减少输出中不太可能的令牌的影响。较高的值（例如，2.0）将更多地减少影响，而值为 1.0 则禁用此设置。 | 1.0
| spring.ai.ollama.embedding.options.typical-p         | -                                                             | 1.0
| spring.ai.ollama.embedding.options.repeat-last-n     | 设置模型回溯以防止重复的距离。（默认：64，0 = 禁用，-1 = num_ctx） | 64
| spring.ai.ollama.embedding.options.temperature       | 模型的温度。增加温度将使模型回答更具创造性。 | 0.8
| spring.ai.ollama.embedding.options.repeat-penalty    | 设置对重复的惩罚强度。较高的值（例如，1.5）将更强烈地惩罚重复，而较低的值（例如，0.9）将更宽容。 | 1.1
| spring.ai.ollama.embedding.options.presence-penalty  | -                                                             | 0.0
| spring.ai.ollama.embedding.options.frequency-penalty | -                                                             | 0.0
| spring.ai.ollama.embedding.options.mirostat          | 启用 Mirostat 采样以控制困惑度。（默认：0，0 = 禁用，1 = Mirostat，2 = Mirostat 2.0） | 0
| spring.ai.ollama.embedding.options.mirostat-tau      | 控制输出的一致性和多样性之间的平衡。较低的值将导致更专注和一致的文本。 | 5.0
| spring.ai.ollama.embedding.options.mirostat-eta      | 影响算法对生成文本反馈的响应速度。较低的学习率将导致较慢的调整，而较高的学习率将使算法更具响应性。 | 0.1
| spring.ai.ollama.embedding.options.penalize-newline  | -                                                             | true
| spring.ai.ollama.embedding.options.stop              | 设置要使用的停止序列。当遇到此模式时，LLM 将停止生成文本并返回。可以通过在 modelfile 中指定多个单独的停止参数来设置多个停止模式。 | -
| spring.ai.ollama.embedding.options.functions         | 要在单个提示请求中启用的函数调用函数列表，由其名称标识。具有这些名称的函数必须存在于 functionCallbacks 注册表中。 | -
|====

提示：所有以 `spring.ai.ollama.embedding.options` 为前缀的属性都可以通过在 `EmbeddingRequest` 调用中添加请求特定的 <<embedding-options>> 在运行时被覆盖。

== 运行时选项 [[embedding-options]]

https://github.com/spring-projects/spring-ai/blob/main/models/spring-ai-ollama/src/main/java/org/springframework/ai/ollama/api/OllamaOptions.java[OllamaOptions.java] 提供了 Ollama 配置，例如要使用的模型、低级 GPU 和 CPU 调优等。

默认选项也可以使用 `spring.ai.ollama.embedding.options` 属性进行配置。

在启动时使用 `OllamaEmbeddingModel(OllamaApi ollamaApi, OllamaOptions defaultOptions)` 配置用于所有嵌入请求的默认选项。
在运行时，您可以通过在 `EmbeddingRequest` 中使用 `OllamaOptions` 实例来覆盖默认选项。

例如，要为特定请求覆盖默认模型名称：

[source,java]
----
EmbeddingResponse embeddingResponse = embeddingModel.call(
    new EmbeddingRequest(List.of("Hello World", "World is big and salvation is near"),
        OllamaOptions.builder()
            .model("Different-Embedding-Model-Deployment-Name"))
            .truncates(false)
            .build());
----

[[auto-pulling-models]]
== 自动拉取模型

Spring AI Ollama 可以在模型在您的 Ollama 实例中不可用时自动拉取模型。
此功能对于开发和测试以及将应用程序部署到新环境特别有用。

提示：您还可以按名称拉取任何数千个免费的 link:https://huggingface.co/models?library=gguf&sort=trending[GGUF Hugging Face 模型]。

拉取模型有三种策略：

* `always`（在 `PullModelStrategy.ALWAYS` 中定义）：始终拉取模型，即使它已经可用。用于确保您使用的是模型的最新版本。
* `when_missing`（在 `PullModelStrategy.WHEN_MISSING` 中定义）：仅在模型不可用时拉取。这可能导致使用较旧版本的模型。
* `never`（在 `PullModelStrategy.NEVER` 中定义）：从不自动拉取模型。

警告：由于下载模型时可能存在延迟，不建议在生产环境中使用自动拉取。相反，考虑提前评估和预下载必要的模型。

所有通过配置属性和默认选项定义的模型都可以在启动时自动拉取。
您可以使用配置属性配置拉取策略、超时和最大重试次数：

[source,yaml]
----
spring:
  ai:
    ollama:
      init:
        pull-model-strategy: always
        timeout: 60s
        max-retries: 1
----

警告：在所有指定的模型在 Ollama 中可用之前，应用程序将不会完成其初始化。根据模型大小和互联网连接速度，这可能会显著减慢应用程序的启动时间。

您可以在启动时初始化其他模型，这对于在运行时动态使用的模型很有用：

[source,yaml]
----
spring:
  ai:
    ollama:
      init:
        pull-model-strategy: always
        embedding:
          additional-models:
            - mxbai-embed-large
            - nomic-embed-text
----

如果您想仅对特定类型的模型应用拉取策略，您可以从初始化任务中排除嵌入模型：

[source,yaml]
----
spring:
  ai:
    ollama:
      init:
        pull-model-strategy: always
        embedding:
          include: false
----

此配置将拉取策略应用于除嵌入模型之外的所有模型。

== HuggingFace 模型

Ollama 可以开箱即用地访问所有 https://huggingface.co/models?library=gguf&sort=trending[GGUF Hugging Face] 嵌入模型。
您可以通过名称拉取这些模型中的任何一个：`ollama pull hf.co/<username>/<model-repository>` 或配置自动拉取策略：xref:auto-pulling-models[自动拉取模型]：

[source]
----
spring.ai.ollama.embedding.options.model=hf.co/mixedbread-ai/mxbai-embed-large-v1
spring.ai.ollama.init.pull-model-strategy=always
----

- `spring.ai.ollama.embedding.options.model`：指定要使用的 https://huggingface.co/models?library=gguf&sort=trending[Hugging Face GGUF 模型]。 
- `spring.ai.ollama.init.pull-model-strategy=always`：（可选）在启动时启用自动模型拉取。 
对于生产环境，您应该预下载模型以避免延迟：`ollama pull hf.co/mixedbread-ai/mxbai-embed-large-v1`。

== 示例控制器

这将创建一个 `EmbeddingModel` 实现，您可以将其注入到您的类中。
以下是一个使用 `EmbeddingModel` 实现的简单 `@Controller` 类示例。

[source,java]
----
@RestController
public class EmbeddingController {

    private final EmbeddingModel embeddingModel;

    @Autowired
    public EmbeddingController(EmbeddingModel embeddingModel) {
        this.embeddingModel = embeddingModel;
    }

    @GetMapping("/ai/embedding")
    public Map embed(@RequestParam(value = "message", defaultValue = "Tell me a joke") String message) {
        EmbeddingResponse embeddingResponse = this.embeddingModel.embedForResponse(List.of(message));
        return Map.of("embedding", embeddingResponse);
    }
}
----

== 手动配置

如果您不使用 Spring Boot，您可以手动配置 `OllamaEmbeddingModel`。
为此，请在项目的 Maven pom.xml 或 Gradle `build.gradle` 构建文件中添加 spring-ai-ollama 依赖：

[tabs]
======
Maven::
+
[source,xml]
----
<dependency>
    <groupId>org.springframework.ai</groupId>
    <artifactId>spring-ai-ollama</artifactId>
</dependency>
----

Gradle::
+
[source,groovy]
----
dependencies {
    implementation 'org.springframework.ai:spring-ai-ollama'
}
----
======

提示：请参考 xref:getting-started.adoc#dependency-management[依赖管理] 部分，将 Spring AI BOM 添加到您的构建文件中。

注意：`spring-ai-ollama` 依赖还提供对 `OllamaChatModel` 的访问。
有关 `OllamaChatModel` 的更多信息，请参考 link:../chat/ollama-chat.html[Ollama 聊天客户端] 部分。

接下来，创建一个 `OllamaEmbeddingModel` 实例并使用它来计算两个输入文本的嵌入，使用专用的 `chroma/all-minilm-l6-v2-f32` 嵌入模型：

[source,java]
----
var ollamaApi = OllamaApi.builder().build();

var embeddingModel = new OllamaEmbeddingModel(this.ollamaApi,
        OllamaOptions.builder()
			.model(OllamaModel.MISTRAL.id())
            .build());

EmbeddingResponse embeddingResponse = this.embeddingModel.call(
    new EmbeddingRequest(List.of("Hello World", "World is big and salvation is near"),
        OllamaOptions.builder()
            .model("chroma/all-minilm-l6-v2-f32"))
            .truncate(false)
            .build());
----

`OllamaOptions` 提供所有嵌入请求的配置信息。
