= PostgresML 嵌入模型

Spring AI 支持 PostgresML 文本嵌入模型。

嵌入是文本的数值表示。
它们用于将单词和句子表示为向量，即数字数组。
嵌入可用于通过使用距离度量比较数值向量的相似性来查找相似的文本片段，或者它们可以用作其他机器学习模型的输入特征，因为大多数算法不能直接使用文本。

许多预训练的 LLM 可以在 PostgresML 中用于从文本生成嵌入。
你可以在 Hugging Face 上浏览所有可用的 https://huggingface.co/models?library=sentence-transformers[模型] 以找到最佳解决方案。

== 添加仓库和 BOM

Spring AI 构件发布在 Maven Central 和 Spring Snapshot 仓库中。
请参阅 xref:getting-started.adoc#artifact-repositories[构件仓库] 部分，将这些仓库添加到你的构建系统中。

为了帮助依赖管理，Spring AI 提供了 BOM（物料清单）以确保在整个项目中使用一致版本的 Spring AI。请参阅 xref:getting-started.adoc#dependency-management[依赖管理] 部分，将 Spring AI BOM 添加到你的构建系统中。

== 自动配置

[NOTE]
====
Spring AI 自动配置、starter 模块的构件名称发生了重大变化。
请参阅 https://docs.spring.io/spring-ai/reference/upgrade-notes.html[升级说明] 了解更多信息。
====

Spring AI 为 Azure PostgresML 嵌入模型提供了 Spring Boot 自动配置。
要启用它，请将以下依赖项添加到项目的 Maven `pom.xml` 文件中：

[source, xml]
----
<dependency>
    <groupId>org.springframework.ai</groupId>
    <artifactId>spring-ai-starter-model-postgresml-embedding</artifactId>
</dependency>
----

或添加到 Gradle `build.gradle` 构建文件中。

[source,groovy]
----
dependencies {
    implementation 'org.springframework.ai:spring-ai-starter-model-postgresml-embedding'
}
----

提示：请参阅 xref:getting-started.adoc#dependency-management[依赖管理] 部分，将 Spring AI BOM 添加到你的构建文件中。

使用 `spring.ai.postgresml.embedding.options.*` 属性来配置你的 `PostgresMlEmbeddingModel`。

=== 嵌入属性

[NOTE]
====
嵌入自动配置的启用和禁用现在通过前缀为 `spring.ai.model.embedding` 的顶级属性进行配置。

要启用，spring.ai.model.embedding=postgresml（默认启用）

要禁用，spring.ai.model.embedding=none（或任何不匹配 postgresml 的值）

此更改是为了允许多个模型的配置。
====

前缀 `spring.ai.postgresml.embedding` 是配置 PostgresML 嵌入的 `EmbeddingModel` 实现的属性前缀。

[cols="3,5,1", stripes=even]
|====
| 属性 | 描述 | 默认值
| spring.ai.postgresml.embedding.enabled（已移除且不再有效） | 启用 PostgresML 嵌入模型。  | true
| spring.ai.model.embedding | 启用 PostgresML 嵌入模型。  | postgresml
| spring.ai.postgresml.embedding.create-extension | 执行 SQL 'CREATE EXTENSION IF NOT EXISTS pgml' 以启用扩展 | false
| spring.ai.postgresml.embedding.options.transformer  | 用于嵌入的 Hugging Face transformer 模型。  | distilbert-base-uncased
| spring.ai.postgresml.embedding.options.kwargs   | 额外的 transformer 特定选项。  | empty map
| spring.ai.postgresml.embedding.options.vectorType   | 用于嵌入的 PostgresML 向量类型。支持两个选项：`PG_ARRAY` 和 `PG_VECTOR`。 | PG_ARRAY
| spring.ai.postgresml.embedding.options.metadataMode   | 文档元数据聚合模式  | EMBED
|====

提示：所有以 `spring.ai.postgresml.embedding.options` 为前缀的属性都可以通过在 `EmbeddingRequest` 调用中添加请求特定的 <<embedding-options>> 在运行时被覆盖。

== 运行时选项 [[embedding-options]]

使用 https://github.com/spring-projects/spring-ai/blob/main/models/spring-ai-openai/src/main/java/org/springframework/ai/postgresml/PostgresMlEmbeddingOptions.java[PostgresMlEmbeddingOptions.java] 来配置 `PostgresMlEmbeddingModel` 的选项，例如要使用的模型等。

在启动时，你可以将 `PostgresMlEmbeddingOptions` 传递给 `PostgresMlEmbeddingModel` 构造函数，以配置用于所有嵌入请求的默认选项。

在运行时，你可以通过在 `EmbeddingRequest` 中使用 `PostgresMlEmbeddingOptions` 来覆盖默认选项。

例如，为特定请求覆盖默认模型名称：

[source,java]
----

EmbeddingResponse embeddingResponse = embeddingModel.call(
    new EmbeddingRequest(List.of("Hello World", "World is big and salvation is near"),
            PostgresMlEmbeddingOptions.builder()
                .transformer("intfloat/e5-small")
                .vectorType(VectorType.PG_ARRAY)
                .kwargs(Map.of("device", "gpu"))
                .build()));
----

== 示例控制器

这将创建一个 `EmbeddingModel` 实现，你可以将其注入到你的类中。
以下是一个使用 `EmbeddingModel` 实现的简单 `@Controller` 类示例。

[source,application.properties]
----
spring.ai.postgresml.embedding.options.transformer=distilbert-base-uncased
spring.ai.postgresml.embedding.options.vectorType=PG_ARRAY
spring.ai.postgresml.embedding.options.metadataMode=EMBED
spring.ai.postgresml.embedding.options.kwargs.device=cpu
----

[source,java]
----
@RestController
public class EmbeddingController {

    private final EmbeddingModel embeddingModel;

    @Autowired
    public EmbeddingController(EmbeddingModel embeddingModel) {
        this.embeddingModel = embeddingModel;
    }

    @GetMapping("/ai/embedding")
    public Map embed(@RequestParam(value = "message", defaultValue = "Tell me a joke") String message) {
        EmbeddingResponse embeddingResponse = this.embeddingModel.embedForResponse(List.of(message));
        return Map.of("embedding", embeddingResponse);
    }
}
----

== 手动配置

不使用 Spring Boot 自动配置，你可以手动创建 `PostgresMlEmbeddingModel`。
为此，将 `spring-ai-postgresml` 依赖项添加到项目的 Maven `pom.xml` 文件中：

[source, xml]
----
<dependency>
    <groupId>org.springframework.ai</groupId>
    <artifactId>spring-ai-postgresml</artifactId>
</dependency>
----

或添加到 Gradle `build.gradle` 构建文件中。

[source,groovy]
----
dependencies {
    implementation 'org.springframework.ai:spring-ai-postgresml'
}
----

提示：请参阅 xref:getting-started.adoc#dependency-management[依赖管理] 部分，将 Spring AI BOM 添加到你的构建文件中。

接下来，创建一个 `PostgresMlEmbeddingModel` 实例并使用它来计算两个输入文本之间的相似度：

[source,java]
----
var jdbcTemplate = new JdbcTemplate(dataSource); // 你的 posgresml 数据源

PostgresMlEmbeddingModel embeddingModel = new PostgresMlEmbeddingModel(this.jdbcTemplate,
        PostgresMlEmbeddingOptions.builder()
            .transformer("distilbert-base-uncased") // huggingface transformer 模型名称。
            .vectorType(VectorType.PG_VECTOR) //PostgreSQL 中的向量类型。
            .kwargs(Map.of("device", "cpu")) // 可选参数。
            .metadataMode(MetadataMode.EMBED) // 文档元数据模式。
            .build());

embeddingModel.afterPropertiesSet(); // 初始化 jdbc 模板和数据库。

EmbeddingResponse embeddingResponse = this.embeddingModel
	.embedForResponse(List.of("Hello World", "World is big and salvation is near"));
----

注意：手动创建时，你必须在设置属性后并在使用客户端之前调用 `afterPropertiesSet()`。
将 PostgresMlEmbeddingModel 创建为 `@Bean` 会更方便（也更推荐）。
这样你就不必手动调用 `afterPropertiesSet()`：

[source,java]
----
@Bean
public EmbeddingModel embeddingModel(JdbcTemplate jdbcTemplate) {
    return new PostgresMlEmbeddingModel(jdbcTemplate,
        PostgresMlEmbeddingOptions.builder()
             ....
            .build());
}
----


