= Azure OpenAI 转录

Spring AI 支持 https://learn.microsoft.com/en-us/azure/ai-services/openai/whisper-quickstart?tabs=command-line%2Cpython-new&pivots=rest-api[Azure Whisper 模型]。

== 前置条件

请在 https://portal.azure.com[Azure Portal] 的 Azure OpenAI 服务部分获取 Azure OpenAI 的 `endpoint` 和 `api-key`。
Spring AI 定义了一个名为 `spring.ai.azure.openai.api-key` 的配置属性，你应将其设置为从 Azure 获取的 API Key。
还有一个名为 `spring.ai.azure.openai.endpoint` 的配置属性，你应将其设置为在 Azure 中配置模型时获得的 endpoint URL。
导出环境变量是一种设置这些配置属性的方式：

== 自动配置

[NOTE]
====
Spring AI 自动配置和 starter 模块的 artifact 名称发生了重大变化。
详情请参考 https://docs.spring.io/spring-ai/reference/upgrade-notes.html[升级说明]。
====

Spring AI 为 Azure OpenAI 转录生成客户端提供了 Spring Boot 自动配置。
要启用它，请在项目的 Maven `pom.xml` 文件中添加如下依赖：

[source,xml]
----
<dependency>
    <groupId>org.springframework.ai</groupId>
    <artifactId>spring-ai-starter-model-azure-openai</artifactId>
</dependency>
----

或在 Gradle `build.gradle` 文件中：

[source,groovy]
----
dependencies {
    implementation 'org.springframework.ai:spring-ai-starter-model-azure-openai'
}
----

TIP: 依赖管理请参考 xref:getting-started.adoc#dependency-management[Dependency Management] 部分。

=== 转录属性

[NOTE]
====
音频转录自动配置的启用和禁用现在通过顶级属性 `spring.ai.model.audio.transcription` 配置。

启用：spring.ai.model.audio.transcription=azure-openai（默认已启用）

禁用：spring.ai.model.audio.transcription=none（或任何不匹配 azure-openai 的值）

此更改允许配置多个模型。
====

前缀 `spring.ai.openai.audio.transcription` 用于配置 OpenAI 图像模型的重试机制。

[cols="3,5,2"]
|====
| 属性 | 描述 | 默认值

| spring.ai.azure.openai.audio.transcription.enabled（已移除，不再有效）  | 启用 Azure OpenAI 转录模型。 | true
| spring.ai.model.audio.transcription  | 启用 Azure OpenAI 转录模型。 | azure-openai
| spring.ai.azure.openai.audio.transcription.options.model  | 要使用的模型 ID。目前仅支持 whisper。 | whisper
| spring.ai.azure.openai.audio.transcription.options.deployment-name  | 部署模型时的部署名称。 |
| spring.ai.azure.openai.audio.transcription.options.response-format | 转录输出的格式，可选项有：json、text、srt、verbose_json 或 vtt。 | json
| spring.ai.azure.openai.audio.transcription.options.prompt | 可选文本，用于引导模型风格或延续先前音频片段。提示应与音频语言一致。 |
| spring.ai.azure.openai.audio.transcription.options.language | 输入音频的语言。以 ISO-639-1 格式提供输入语言可提升准确性和延迟表现。 |
| spring.ai.azure.openai.audio.transcription.options.temperature | 采样温度，范围 0 到 1。较高值如 0.8 使输出更随机，较低值如 0.2 使输出更集中和确定。若设为 0，模型将使用对数概率自动提升温度直到达到某些阈值。 | 0
| spring.ai.azure.openai.audio.transcription.options.timestamp-granularities | 要为本次转录填充的时间戳粒度。response_format 必须设置为 verbose_json 才能使用时间戳粒度。支持 word 或 segment。注意：segment 时间戳无额外延迟，但生成 word 时间戳会增加延迟。 | segment
|====

== 运行时选项

`AzureOpenAiAudioTranscriptionOptions` 类提供了进行转录时可用的选项。
启动时使用 `spring.ai.azure.openai.audio.transcription` 指定的选项，但你可以在运行时覆盖。

例如：

[source,java]
----
AzureOpenAiAudioTranscriptionOptions.TranscriptResponseFormat responseFormat = AzureOpenAiAudioTranscriptionOptions.TranscriptResponseFormat.VTT;

AzureOpenAiAudioTranscriptionOptions transcriptionOptions = AzureOpenAiAudioTranscriptionOptions.builder()
    .language("en")
    .prompt("Ask not this, but ask that")
    .temperature(0f)
    .responseFormat(this.responseFormat)
    .build();
AudioTranscriptionPrompt transcriptionRequest = new AudioTranscriptionPrompt(audioFile, this.transcriptionOptions);
AudioTranscriptionResponse response = azureOpenAiTranscriptionModel.call(this.transcriptionRequest);
----

== 手动配置

在项目的 Maven `pom.xml` 文件中添加 `spring-ai-openai` 依赖：

[source,xml]
----
<dependency>
    <groupId>org.springframework.ai</groupId>
    <artifactId>spring-ai-azure-openai</artifactId>
</dependency>
----

或在 Gradle `build.gradle` 文件中：

[source,groovy]
----
dependencies {
    implementation 'org.springframework.ai:spring-ai-azure-openai'
}
----

TIP: 依赖管理请参考 xref:getting-started.adoc#dependency-management[Dependency Management] 部分。

接下来，创建 `AzureOpenAiAudioTranscriptionModel`

[source,java]
----
var openAIClient = new OpenAIClientBuilder()
    .credential(new AzureKeyCredential(System.getenv("AZURE_OPENAI_API_KEY")))
    .endpoint(System.getenv("AZURE_OPENAI_ENDPOINT"))
    .buildClient();

var azureOpenAiAudioTranscriptionModel = new AzureOpenAiAudioTranscriptionModel(this.openAIClient, null);

var transcriptionOptions = AzureOpenAiAudioTranscriptionOptions.builder()
    .responseFormat(TranscriptResponseFormat.TEXT)
    .temperature(0f)
    .build();

var audioFile = new FileSystemResource("/path/to/your/resource/speech/jfk.flac");

AudioTranscriptionPrompt transcriptionRequest = new AudioTranscriptionPrompt(this.audioFile, this.transcriptionOptions);
AudioTranscriptionResponse response = this.azureOpenAiAudioTranscriptionModel.call(this.transcriptionRequest);
----
