== OpenAI 转录

Spring AI 支持 https://platform.openai.com/docs/api-reference/audio/createTranscription[OpenAI 的转录模型]。

== 前置条件

你需要创建 OpenAI API 密钥以访问 ChatGPT 模型。
请在 https://platform.openai.com/signup[OpenAI 注册页面] 注册账号，并在 https://platform.openai.com/account/api-keys[API 密钥页面] 生成令牌。
Spring AI 项目定义了一个名为 `spring.ai.openai.api-key` 的配置属性，你应将其设置为从 openai.com 获取的 API Key。
导出环境变量是一种设置该配置属性的方式：

== 自动配置

[NOTE]
====
Spring AI 自动配置和 starter 模块的 artifact 名称发生了重大变化。
详情请参考 https://docs.spring.io/spring-ai/reference/upgrade-notes.html[升级说明]。
====

Spring AI 为 OpenAI 转录客户端提供了 Spring Boot 自动配置。
要启用它，请在项目的 Maven `pom.xml` 文件中添加如下依赖：

[source, xml]
----
<dependency>
    <groupId>org.springframework.ai</groupId>
    <artifactId>spring-ai-starter-model-openai</artifactId>
</dependency>
----

或在 Gradle `build.gradle` 文件中：

[source,groovy]
----
dependencies {
    implementation 'org.springframework.ai:spring-ai-starter-model-openai'
}
----

TIP: 依赖管理请参考 xref:getting-started.adoc#dependency-management[Dependency Management] 部分。

=== 转录属性

==== 连接属性

前缀 `spring.ai.openai` 用于连接 OpenAI。

[cols="3,5,1"]
|====
| 属性 | 描述 | 默认值
| spring.ai.openai.base-url   | 连接的 URL |  https://api.openai.com
| spring.ai.openai.api-key    | API 密钥   |  -
| spring.ai.openai.organization-id | 可选，指定 API 请求使用的组织 |  -
| spring.ai.openai.project-id      | 可选，指定 API 请求使用的项目 |  -
|====

TIP: 对于属于多个组织的用户（或通过旧版用户 API 密钥访问项目），可选地指定 API 请求使用的组织和项目。
这些 API 请求的用量将计入指定的组织和项目。

==== 配置属性

[NOTE]
====
音频转录自动配置的启用和禁用现在通过顶级属性 `spring.ai.model.audio.transcription` 配置。

启用：spring.ai.model.audio.transcription=openai（默认已启用）

禁用：spring.ai.model.audio.transcription=none（或任何不匹配 openai 的值）

此更改允许配置多个模型。
====

前缀 `spring.ai.openai.audio.transcription` 用于配置 OpenAI 转录模型的重试机制。

[cols="3,5,2"]
|====
| 属性 | 描述 | 默认值

| spring.ai.model.audio.transcription   | 启用 OpenAI 音频转录模型 |  openai
| spring.ai.openai.audio.transcription.base-url   | 连接的 URL |  https://api.openai.com
| spring.ai.openai.audio.transcription.api-key    | API 密钥   |  -
| spring.ai.openai.audio.transcription.organization-id | 可选，指定 API 请求使用的组织 |  -
| spring.ai.openai.audio.transcription.project-id      | 可选，指定 API 请求使用的项目 |  -
| spring.ai.openai.audio.transcription.options.model  | 要使用的模型 ID。目前仅支持 whisper-1（基于开源 Whisper V2 模型）。 |  whisper-1
| spring.ai.openai.audio.transcription.options.response-format | 转录输出的格式，可选项有：json、text、srt、verbose_json 或 vtt。 |  json
| spring.ai.openai.audio.transcription.options.prompt | 可选文本，用于引导模型风格或延续先前音频片段。提示应与音频语言一致。 |
| spring.ai.openai.audio.transcription.options.language | 输入音频的语言。以 ISO-639-1 格式提供输入语言可提升准确性和延迟表现。 |
| spring.ai.openai.audio.transcription.options.temperature | 采样温度，范围 0 到 1。较高值如 0.8 使输出更随机，较低值如 0.2 使输出更集中和确定。若设为 0，模型将使用对数概率自动提升温度直到达到某些阈值。 | 0
| spring.ai.openai.audio.transcription.options.timestamp_granularities | 要为本次转录填充的时间戳粒度。response_format 必须设置为 verbose_json 才能使用时间戳粒度。支持 word 或 segment。注意：segment 时间戳无额外延迟，但生成 word 时间戳会增加延迟。 | segment
|====

NOTE: 你可以覆盖通用的 `spring.ai.openai.base-url`、`spring.ai.openai.api-key`、`spring.ai.openai.organization-id` 和 `spring.ai.openai.project-id` 属性。
如果设置了 `spring.ai.openai.audio.transcription.base-url`、`spring.ai.openai.audio.transcription.api-key`、`spring.ai.openai.audio.transcription.organization-id` 和 `spring.ai.openai.audio.transcription.project-id`，则优先生效。
这对于为不同模型和端点使用不同 OpenAI 账号很有用。

TIP: 所有以 `spring.ai.openai.transcription.options` 为前缀的属性都可以在运行时覆盖。

== 运行时选项 [[transcription-options]]

`OpenAiAudioTranscriptionOptions` 类提供了进行转录时可用的选项。
启动时使用 `spring.ai.openai.audio.transcription` 指定的选项，但你可以在运行时覆盖。

例如：

[source,java]
----
OpenAiAudioApi.TranscriptResponseFormat responseFormat = OpenAiAudioApi.TranscriptResponseFormat.VTT;

OpenAiAudioTranscriptionOptions transcriptionOptions = OpenAiAudioTranscriptionOptions.builder()
    .language("en")
    .prompt("Ask not this, but ask that")
    .temperature(0f)
    .responseFormat(this.responseFormat)
    .build();
AudioTranscriptionPrompt transcriptionRequest = new AudioTranscriptionPrompt(audioFile, this.transcriptionOptions);
AudioTranscriptionResponse response = openAiTranscriptionModel.call(this.transcriptionRequest);
----

== 手动配置

在项目的 Maven `pom.xml` 文件中添加 `spring-ai-openai` 依赖：

[source, xml]
----
<dependency>
    <groupId>org.springframework.ai</groupId>
    <artifactId>spring-ai-openai</artifactId>
</dependency>
----

或在 Gradle `build.gradle` 文件中：

[source,groovy]
----
dependencies {
    implementation 'org.springframework.ai:spring-ai-openai'
}
----

TIP: 依赖管理请参考 xref:getting-started.adoc#dependency-management[Dependency Management] 部分。

接下来，创建 `OpenAiAudioTranscriptionModel`

[source,java]
----
var openAiAudioApi = new OpenAiAudioApi(System.getenv("OPENAI_API_KEY"));

var openAiAudioTranscriptionModel = new OpenAiAudioTranscriptionModel(this.openAiAudioApi);

var transcriptionOptions = OpenAiAudioTranscriptionOptions.builder()
    .responseFormat(TranscriptResponseFormat.TEXT)
    .temperature(0f)
    .build();

var audioFile = new FileSystemResource("/path/to/your/resource/speech/jfk.flac");

AudioTranscriptionPrompt transcriptionRequest = new AudioTranscriptionPrompt(this.audioFile, this.transcriptionOptions);
AudioTranscriptionResponse response = openAiTranscriptionModel.call(this.transcriptionRequest);
----

== 示例代码
* link:https://github.com/spring-projects/spring-ai/blob/main/models/spring-ai-openai/src/test/java/org/springframework/ai/openai/audio/transcription/OpenAiTranscriptionModelIT.java[OpenAiTranscriptionModelIT.java] 测试提供了一般用法示例。
